### ISSUE TITLE
Git config commands not working

### ISSUE THREAD

**Issue by dan-bowerman** [githubteacher/intermediate-april-2015#13]
I can config my user email and name, but some of the other commands are not working (Windows):
For example:
C:\Users\DanB\Documents\GitHub> git config color.ui auto
error: could not lock config file .git/config: No such file or directory

What have I done wrong?

**Comment by marek-janicki** [comment]
I found adding the --global flag fixed this for me.

**Comment by pcharlan** [comment]
Yes, the default is --local, which only works if you're in a repo (because it modifies the config for that repo only).  If you want to modify your ~/.gitconfig file, global to all your repos, you need --global.

**Comment by dan-bowerman** [comment]
Got it, thanks!

**Comment by ammello46** [comment]
I had the same problem and it worked with --global

**Comment by crichID** [comment]
@pcharlan @ammello46 thank you both for jumping in to help your fellow classmates :sparkles:
