### ISSUE TITLE
HEAD : last committed work, or commit on top of which the *next commit* will be built..?

### ISSUE THREAD

**Issue by nrolland** [githubteacher/intermediate-april-2015#17]
I think I can put HEAD anywhere. it happens that the behaviour puts it in the last position, but thats just a convention, there is no guarantee.

**Comment by crichID** [comment]
You do have some control over the location of the HEAD - however these are topics we will not discuss until tomorrow's Advanced class!

**Comment by nrolland** [comment]
While waiting for a discussion in advanced training, AFAIK the only thing defining HEAD you can count on is that it will be the ancestor of the next commit. anything else just happens to be an 'accidental' property

**Comment by githubteacher** [comment]
@nrolland HEAD is a pointer, and by default it points to your current branch. You almost always want to keep it that way. There are operations that require you to unset HEAD, and get into what's called a "detached HEAD" state, e.g. during `git rebase`, but you can get into trouble quickly if you don't know what you're doing.

**Comment by nrolland** [comment]
You might want to keep it that way, but you might also make an unwilling mistake and end up not that way. 

If you bear in mind that there is nothing special except that it is the ancestor of your next commit, there is no problem. if you read that it is the "last stuff in your line of work" and its not there, you are confused and panicked....

Why define it by what it is not ? I'd rather say that "unless you requested it, it should naturally point happen to be your last line of work" ...

Anywway, you guys know better, but I think it is confusing.
