### ISSUE TITLE
new repo 

### ISSUE THREAD

**Issue by Pritesh23** [githubteacher/intermediate-april-2015#20]
Can you please repeat licence and new repo steps? I didnt create second repo because of lic issue.

**Comment by githubteacher** [comment]
@Pritesh23 Here is a link that contains the steps he covered:

[Create A Repo](https://help.github.com/articles/create-a-repo/)

And a link to more information about licenses:

[Choosing an OSS License](http://choosealicense.com/)

**Comment by Pritesh23** [comment]
it works !! thanks
