### ISSUE TITLE
how do i use command line on windows github?

### ISSUE THREAD

**Issue by rickyrey** [githubteacher/intermediate-april-2015#22]

**Comment by githubteacher** [comment]
The easiest way to download and install Git on your windows machine is by downloading [GitHub for Windows](https://windows.github.com/)

You will also need a command line program like PowerShell.

**Comment by githubteacher** [comment]
You can also download the Windows version of git (called MySysGit) [here](http://msysgit.github.io/)

**Comment by rickyrey** [comment]
Thanks
