### ISSUE TITLE
Why would a repo not have a "Clone" box, giving the URL?

### ISSUE THREAD

**Issue by pcharlan** [githubteacher/intermediate-april-2015#23]
I created https://github.com/pcharlan/recipes-april-pete and pushed to it from my repo on my desktop.  I don't see the "HTTPS clone URL" box on the GitHub page; why?

**Comment by githubteacher** [comment]
@pcharlan And you're logged into GitHub? I can see it on the right side, towards the bottom:

![screen shot 2015-04-29 at 9 56 32 am](https://cloud.githubusercontent.com/assets/2132216/7396471/14fcaae6-ee56-11e4-914f-4ca03c322084.png)

**Comment by githubteacher** [comment]
@pcharlan One thing that sometimes gets students is that they are in a view other than the code view - you must be in code view to see the Clone options!

**Comment by pcharlan** [comment]
I'm in the code view and logged in:

![screen shot 2015-04-29 at 10 01 37 am](https://cloud.githubusercontent.com/assets/8455465/7396545/d30893e2-ee56-11e4-9172-47e2b5d98535.png)

**Comment by githubteacher** [comment]
It has to be some sort of repo setting because I noticed that the Fork option also does not appear!  Would you happen to be on your company's instance of GHE?

**Comment by githubteacher** [comment]
Oh - nevermind - dumb question! - looking for an answer!

**Comment by githubteacher** [comment]
@pcharlan can you please tell me which browser and version you are using?

**Comment by pcharlan** [comment]
Interestingly, reloading the page didn't help, but shift-reload did.  This is Chrome 41.0.2272.118 on Mac OS X 10.9.5.

**Comment by githubteacher** [comment]
@pcharlan great - I'm glad it is working now. That is weird and I will forward it to some of my colleagues who can take a look. In the meantime, the URL at the top of the page is actually the same as the clone URL. You just need to add `.git` to the end!
