### ISSUE TITLE
git push -u origin master failed when doing from remote with out clonning

### ISSUE THREAD

**Issue by arjun911code** [githubteacher/intermediate-april-2015#25]
git push -u origin master failed when doing from remote with out clonning. But works while clonning the remote locally then pushing

**Comment by githubteacher** [comment]
Just to confirm I understand, did you do the following steps:
- `git clone <URL>`
- `cd <DIR>`
- make some changes
- `git add .`
- `git commit -m"message"`
- `git push -u origin master`?

Were you working on a branch? Or master? Can you copy/paste the error?
