### ISSUE TITLE
What is the difference between ignoring local changes using 'git checkout HEAD file' and 'git checkout -- file'?

### ISSUE THREAD

**Issue by srikanthchitipotu** [githubteacher/intermediate-april-2015#29]

**Comment by githubteacher** [comment]
`git checkout -- <file>` destroys the changes you made to the file as noted in the staging directory and returns the file to it's previously committed state.

`git reset HEAD <file>` only unstages the file - the changes remain intact but are in the working directory!

**Comment by pcharlan** [comment]
"git checkout HEAD -- file" makes the working copy agree with the HEAD commit, and unstages any changes.  "git checkout -- file" makes the working copy agree with the index (staging area), not HEAD.

The "--" is optional in most cases; it tells Git to not consider interpreting "file" as a branch name or other commit reference.
