### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by narJH27** [githubteacher/intermediate-april-2015#31]
It would be nice to have you explain the standard git workflow and walk through it for a project rather than explain what each flag does. In my personal opinion, the flags can be viewed by a user upon issuing the --help command. 

Could you please focus a bit more on the reason for performing the steps in the workflow a certain way rather than just doing them and explaining the commands instead?

**Comment by HerbNichols** [comment]
+1

**Comment by ironfist** [comment]
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by Pritesh23** [comment]
+1

**Comment by arjun911code** [comment]
please go over :+1:

**Comment by narJH27** [comment]
Yes the third section was much better. But I would really like to see how to integrate all the commands including a rebase which you will cover tomorrow, into a "best-practices" type of workflow, all the way from start to finish, ie, from a git init on the project all the way upto possibly a merge of branches over a period of time, which includes a regular rebase etc ....

Hope I was able to make the intent clear?

**Comment by githubteacher** [comment]
@narJH27 Yes, I certainly understand that. Time is one of the biggest obstacles here. We can only do so much in a 3 hour webinar, compared to a full day of in-person training. But your point is well taken, and we can still do that much better than was done today. 

Thanks for the feedback!
