### ISSUE TITLE
fork and pulling from upstream to local fork and push back change

### ISSUE THREAD

**Issue by arjun911code** [githubteacher/intermediate-april-2015#34]
Please explain how to fork and push back the change to the fork. Also, pullin any changes in upstream to avoid conflict

**Comment by Pritesh23** [comment]
Yes, you are right ! I tried but no access ;)

**Comment by arjun911code** [comment]
but what if the master in the original forked was changed when I am creating a pull request

**Comment by arjun911code** [comment]
do i need to to merge the changes in the electron to my fork before pull request ?

**Comment by githubteacher** [comment]
@arjun911code I believe we covered this on-air, but please re-open the issue this remains unclear.
