### ISSUE TITLE
Path vs non-Path versions of commit and reset

### ISSUE THREAD

**Issue by pcharlan** [githubteacher/intermediate-april-2015#35]
I think it's helpful to mention that checkout with a path is arguably a different command than checkout without a path; ditto reset.  I think the interfaces to those commands are some of the most confusing aspects of the CLI to new users.

Also, I found this blog entry (by Scott Chacon?) helpful when thinking about reset; perhaps it would be useful to others to point to it:

http://git-scm.com/blog/2011/07/11/reset.html

**Comment by githubteacher** [comment]
@pcharlan Thanks for the feedback, I did do a poor job of clarifying that difference. Adding your link to the README.
