### ISSUE TITLE
fetch vs pull vs rebase - difference?

### ISSUE THREAD

**Issue by narJH27** [githubteacher/intermediate-april-2015#36]
Can you explain the difference between a git pull and a git fetch and a git rebase?

**Comment by arjun911code** [comment]
:+1:

**Comment by narJH27** [comment]
Great Explanation! Thank you so much :+1:

**Comment by sreechandran** [comment]
:+1:

**Comment by arjun911code** [comment]
so git pull is actually a fetch and merge to local copy ?

**Comment by githubteacher** [comment]
@arjun911code Yup, if by local copy you mean local tracking branch.

**Comment by nrolland** [comment]
@arjun911code  yes, it updates the "local tracking branches" which are your read only copy at some point in time of the  "remote tracking branches", which lives on another computer, say github
